services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root_user
      MONGO_INITDB_ROOT_PASSWORD: root_user_password

  backend:
    build: ./src/backend  # Build the backend using the Dockerfile
    ports:
      - "5000:5000"  # Expose port 5000 for the backend
    environment:
      MONGO_URI: mongodb://food90_user:food90_user_password@mongodb:27017/food90
    depends_on:
      - mongodb
      
  frontend:
    build: ./src/frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongodb_data: